spring:
  application:
    name: soumen-billing-app
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB_NAME}
management:
  endpoint:
    metrics:
      enabled: ${METRIC_ENABLED:false}
    prometheus:
      enabled: ${PROMETHEUS_ENABLED:false}
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

